create database migramind_a;

drop table if exists tableinfo 

create table tableInfo (
ID SERIAL primary key,
Company VARCHAR(100) NOT NULL,
TITLE VARCHAR(200),
DESCRIPTION VARCHAR(1000),
URL_BASIC VARCHAR(80),
SCHEDULE_DESCRIPTION VARCHAR(350),
URL_SCHEDULE VARCHAR(100),
ADDRESS VARCHAR(120),
PROVINCIE VARCHAR(50),
COUNTRY VARCHAR(50),
EMAIL VARCHAR(100),
PHONE VARCHAR(140),
TYPE_OF_COMPANY VARCHAR(30),
code_photo varchar(20)
);

insert into tableInfo (company, title, description, url_basic, schedule_description, url_schedule, address, provincie, country, email, phone, type_of_company, code_photo) 
values('Ajuntament barcelona CAT ','Practical information for living in the city of Barcelona','Info Barcelona is the website that publishes the news of the Barcelona City Council: the decisions of the municipal Plenary, the actions of the various areas and the most representative initiatives of the ten districts of the city. Practical information for living in the city of Barcelona: news, activities, services, work, transport, business, leisure, maps and innovation.','https://ajuntament.barcelona.cat/','As important as physical health is mental or psychological health:','https://ajuntament.barcelona.cat/joves/es/canal/et-poden-ajudar-i-informar-12','PLAZA SANT JAUME, 2 , 08002','Barcelona','Spain','bigestio@bcn.cat','telefon 010 (from outside Barcelona, 931 537 010) and the service "The Ajuntament calls you", Suicide prevention phone: 900 92 55 55','PUBLIC','0001');

insert into tableInfo (company, title, description, url_basic, schedule_description, url_schedule, address, provincie, country, email, phone, type_of_company, code_photo) 
values('Umbral red asistencial "psi"','Asistance network, made up of psychoanalysts, clinical psychologists, psychiatrists and collaborators from other areas to work on current malaise both in culture and individually.','UMBRAL is constituted as an assistance network, made up of psychoanalysts, clinical psychologists, psychiatrists and collaborators from other areas to work on the current malaise both in culture and individually. UMBRAL proposes itself as a supportive and non-profit network, which offers treatments with accessible fees to people or institutions that request their services. This network circuit puts those who need it in contact with the right professional, allowing demands not to go unattended for economic reasons. Anguish, loneliness, maladjustment, conflicts with others, dependencies, helplessness, lack of love, violence, difficulties with knowing and knowing how to do are some of the painful problems that every subject faces at various moments of a life without power of resolution, and it is there where a professional who knows how to listen to this mental suffering can intervene to propose a cure.','https://www.umbral-red.org/','Clinical care :','https://www.umbral-red.org/es/atencion-clinica.html','C/ de Niça, 3, Local, 08024','Barcelona','Spain','coordinacion@umbral-red.org','Telephone: 934 33 52 33','PUBLIC','0002');

insert into tableInfo (company, title, description, url_basic, schedule_description, url_schedule, address, provincie, country, email, phone, type_of_company, code_photo) 
values('Parc Sanitari Sant Joan de Déu PSSJD','The General Hospital of Sant Boi and Sant Joan de Déu Mental Health Services','The Parc Sanitari de Sant Joan de Déu was born in 2010 from the merger of the General Hospital of Sant Boi and Sant Joan de Déu Mental Health Services; and thanks to the more than 2,000 professionals, it promotes peoples health and autonomy, offering specialized and individualized health and social services, specialized care medical processes, Mental Health processes and socio-sanitary processes, while taking responsibility for caring for people with intellectual disabilities. It is a network of care, teaching and research services. This structure makes it possible to provide comprehensive quality care, both at the health and social level, also promoting a proactive model of community-based services.','https://www.pssjd.org/','Sant Joan de Déu Health Park has a list of programs framed within the health and social field in order to offer the best care to the people it serves. ','https://www.pssjd.org/serveis-assitencials/xarxa-salut-mental/programes','c/ Doctor Antoni Pujadas, 42. 08830','Barcelona','Spain','ParcSanitari.utjj@sjd.es.','TELEPHONE 93 640 63 50','Private','0003');

insert into tableInfo (company, title, description, url_basic, schedule_description, url_schedule, address, provincie, country, email, phone, type_of_company, code_photo) 
values('fundacion BABEL','Private, independent, non-profit charitable foundation','We are dedicated to people. We are an independent, non-profit private foundation of a charitable, social and cultural nature. Through our projects we help improve the quality of life of the people of Barcelona and Senegal. In Barcelona, we offer accompaniment to people in vulnerable situations.','https://www.babelpuntodeencuentro.org/','The Puentes project is intended to offer reception and accompaniment to people who have recently arrived in our society or who at some stage of their lives have experienced a migratory process.','https://www.babelpuntodeencuentro.org/proyecto/proyecto-puentes-4/#acceso','Carrer dels Salvador, 4, 08001 Barcelona','Barcelona','Spain','info@babelpuntodeencuentro.org gestion@babelpuntodeencuentro.org','telephone : +34 93 295 57 93 / +34 629 577 430','Private','0004');


insert into tableInfo (company, title, description, url_basic, schedule_description, url_schedule, address, provincie, country, email, phone, type_of_company, code_photo) 
values('Sant Pere Claver - Fundació Sanitària SPCSALUT','Welcome to the Sant Pere Claver Group, entities with a social commitment.','We are a private non-profit institution with a vocation and public funding, created in 1948. With a long tradition and rooted in the Sants-Montjuïc district, it provides public coverage services in Mental Health, complementary tests and Allergology. At a private level, it has a Dental Clinic and an Ophthalmology service.','https://www.spcsalut.org/','Program specialized in attending to the mental health needs of immigrants and refugees as well as in research, evaluation, supervision and teaching in this area. ','https://www.spcsalut.org/sm-refugiats.php','Carrer de Vila i Vilà ,16 ,08004 ','Barcelona','Spain','info@spcsalut.org','Telephone 934 42 39 03','Private','0005');


insert into tableInfo (company, title, description, url_basic, schedule_description, url_schedule, address, provincie, country, email, phone, type_of_company, code_photo) 
values('terapiasinfronteras ','Psychological Care for Migrants and People of Foreign Origin, Systemic Transcultural Model Training','Association of Transcultural Systemic Psychotherapy. Psychotherapeutic Care for Migrants and people of foreign origin Training in the Transcultural model to be able to evaluate and intervene in psychological problems derived from migration Design and development of Psychosocial Projects','https://terapiasinfronteras.com/','Do you need an online transcultural psychological therapy?','https://terapiasinfronteras.com/terapia-psicologica-online-transcultural/','C. de San Agustín, 7, 1ª Ext Izq, 28014','Madrid','Spain','info@terapiasinfronteras.com','Thelephone :914 299 756 - 653 345 616','Private','0006');


insert into tableInfo (company, title, description, url_basic, schedule_description, url_schedule, address, provincie, country, email, phone, type_of_company, code_photo) 
values('Conexus','The CONEXUS Psychosocial Care, Training and Research Association','The CONEXUS Psychosocial Care, Training and Research Association is made up of psychologists with extensive experience in caring for people in the family, social and health spheres, as well as in training professional teams and in research. The objective of CONEXUS is to improve the well-being and health of people, especially those in situations of difficulty, crisis, violence or inequality.
Through psychosocial care for women, men, girls, boys and adolescents, we want to promote the improvement of affective and family relationships, the eradication of violence, and healthy and egalitarian lifestyles. In addition, we carry out training for professionals, companies and institutions on these matters, and we carry out research, both theoretical and applied, to improve intervention and broaden knowledge.','https://conexus.cat/','Psychotherapy and Programs ','https://conexus.cat/atencio/','Consell de Cent 419 3r 2a – 08009 ','Barcelona','Spain','info@conexus.cat','Telephone : (+34) 93 217 16 46','Private','0007');

insert into tableInfo (company, title, description, url_basic, schedule_description, url_schedule, address, provincie, country, email, phone, type_of_company, code_photo) 
values('Equality ','Equality is a non-profit organization, we strongly believe that mental health care should be accessible to all members of society.','Equality is a non-profit organization registered in Barcelona, Spain, since September 2022. We strongly believe that mental health care should be accessible to all members of society, which is why we offer free mental health services to individuals and communities facing marginalization and precariousness. Together with our local and international partners, we work with a wide range of individuals and groups, including people with refugee backgrounds, people from LGBTIQ+ communities, people facing mental or physical disabilities, people facing economic hardships, or people facing injustice anywhere. another way.','https://iguality.org/','What we offer  ','https://iguality.org/activities/','C/ de la Diputació, 107, 08015 ','Barcelona','Spain','info@iguality.org','Telephone : +34 633 05 69 40','Private','0008');

insert into tableInfo (company, title, description, url_basic, schedule_description, url_schedule, address, provincie, country, email, phone, type_of_company, code_photo) 
values('Asil cat','Asil.cat, a network of organizations in defense of the right to asylum in Catalonia and the rights of people who have suffered forced displacement.','The objective of Asil.cat is to improve the reception capacities of Catalan society. People with international protection needs also come to Catalonia. For this reason, it is necessary to make a good identification so that they can request international protection and can benefit from the different programs and services that are available to them.','http://asil.cat/','ASSOCIATION The EXIL Association is the Asil.cat Network’s member organisation that is concerned with offering medical, psychological and social therapy to those that have suffered from distinct types of human rights violations including torture, persecution, war, forced exile or gender violence. ','http://asil.cat/serveis/medic-psico-social/','Av. Reina Mª Cristina, s/n, 08004','Barcelona','Spain','acathi@acathi.org','Telephone: 910 474 444','Private','0009');